_security_login:
    path:  /login
    defaults: { _controller: DipsycatFbSocialBundle:Security:login }

_security_check:
    path:  /login_check

_security_logout:
    path:  /logout
    
connect_facebook:
    path:  /connect/facebook
    defaults: { _controller: DipsycatFbSocialBundle:FacebookAuth:connectFacebook }

connect_facebook_check:
    path:  /connect/facebook-check
    defaults: { _controller: DipsycatFbSocialBundle:FacebookAuth:connectFacebookCheck }