dipsycat_fb_social_friend_list:
    path:  /friends
    defaults: { _controller: DipsycatFbSocialBundle:Friend:getFriends }

dipsycat_fb_social_friend_remove:
    path:  /friend/remove/{id}
    defaults: { _controller: DipsycatFbSocialBundle:Friend:removeFriend }
