<?php

namespace Dipsycat\FbSocialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimRepository extends EntityRepository {

    public function getClaims($data) {
        $queryBuilder = $this->createQueryBuilder('claim');
        $result = $queryBuilder
                        ->where('claim.createdAt >= :dateStart')
                        ->andWhere('claim.createdAt <= :dateEnd')
                        ->andWhere('claim.status IN (:statuses)')
                        ->setParameters([
                            'dateStart' => $data['dateStart'],
                            'dateEnd' => $data['dateEnd'],
                            'statuses' => $data['status'],
                        ])
                        ->getQuery()->getResult();
        return $result;
    }

}
