<?php

namespace Dipsycat\FbSocialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClaimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimRepository extends EntityRepository {
    
}
