app_topic_chat:
    channel: app/chat/{conversation}
    handler:
        callback: 'app.topic.chat' #Относится к getName, а не к имени сервиса
    requirements:
        conversation:
            pattern: "\d+"